version: "3.7"
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      # node_modulesをdata volumeで保持
      - /app/node_modules
    command: npm run dev
    ports: 
      - 3000:3000      
