# Generated by Django 3.2.7 on 2021-09-28 14:46

import uuid

import timemanager.models.waiting_time_history

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitingTimeHistory",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created_at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated_at")),
                (
                    "waiting_time",
                    models.PositiveSmallIntegerField(
                        validators=[timemanager.models.waiting_time_history.validate_waiting_time], verbose_name="待ち時間"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="展示団体"
                    ),
                ),
            ],
            options={
                "verbose_name": "待ち時間履歴",
                "verbose_name_plural": "待ち時間履歴",
                "ordering": ["-created_at"],
            },
        ),
    ]
